site_name: Evan2you's paper Notes
theme:
  name: material
  language: zh
  #更改小组件
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - nabigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  plugins:
    - typeset
    - search

  palette:

    #深色主题
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    
    #浅色主题
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
   