site_name: Evan2you's Paper Notes

theme:
  name: material
  language: zh
  #更改小组件
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - nabigation.tracking
    - search.highlight
    - search.share
    - search.suggest

  plugins:
    - typeset
    - search

  palette:
   
    #浅色主题
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
   
   #深色主题
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

markdown_extensions: 
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - attr_list
    - md_in_html
    - pymdownx.blocks.caption
    - pymdownx.arithmatex:
        generic: true
    - pymdownx.emoji:
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
        emoji_index: !!python/name:material.extensions.emoji.twemoji
    - toc:
        permalink: true
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    

copyright: Copyright @copy:2024 Evan2you

# extra_css: 
#   - stylesheets/extra.css

#latex公式
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  generator: false

#导航栏  
nav:
  - 'Start Here':
    - 'Start Here': index.md
  - '组会汇报':
    - '2024年11月': 组会汇报/2024年11月.md
    - '2024年12月': 组会汇报/2024年12月.md
  - '论文整理':
    - 'Markdown新手教程': 论文整理/Markdown新手教程.md
    - 'GhostNet': 论文整理/GhostNet.md
    - 'EfficientViT': 论文整理/EfficientViT.md
    - 'SGENet': 论文整理/SGENet.md
    - 'KANNet': 论文整理/KANNet.md
    - '脑电通道选择': 论文整理/脑电通道选择.md
    - '集成学习': 论文整理/集成学习.md
  - '硬件创作':
    - '脑电采集硬件': 硬件创作/脑电采集硬件.md
    - '运动想象qt上位机': 硬件创作/运动想象qt上位机.md
  - '日常分享':
    - '省身之语': 日常分享/省身之语.md
    - '大美女': 日常分享/大美女.md
